### ISSUE TITLE
submodule mirana @ 626634f does not exist

### ISSUE THREAD

**Issue by robbietree8** [trydofor/pro.fessional.wings#3]

**Comment by alanfans** [comment]
https://github.com/trydofor/pro.fessional.mirana

**Comment by alanfans** [comment]
https://github.com/trydofor/pro.fessional.meepo

**Comment by robbietree8** [comment]
I mean the commit 626634f in mirana does not exist

**Comment by alanfans** [comment]
需要自行编译并本地安装  项目地址：https://github.com/trydofor/pro.fessional.mirana
[meepo](https://github.com/trydofor/pro.fessional.meepo)也是同样方式

**Comment by alanfans** [comment]
文档上有写：https://wings.fessional.pro/0-wings/0e-qa-config.html#_0e-04-%E7%BC%BA%E5%B0%91mirana%E5%92%8Cmeepo%E4%BE%9D%E8%B5%96lib

**Comment by robbietree8** [comment]
发现问题所在了，估计是github上的mirana仓库还没更新到最新版本，落后gitee 2个commit。

而github/wings的submodule指向的是最新的commit。

![image](https://user-images.githubusercontent.com/73832691/176990510-f18015e3-0a7f-4945-88a2-14c835b44e2f.png)

![image](https://user-images.githubusercontent.com/73832691/176990525-19d12af6-bbbd-48ab-9e1c-ad8e57fd9734.png)

**Comment by robbietree8** [comment]
发现问题所在了，估计是github上的mirana仓库还没更新到最新版本，落后gitee 2个commit。

而github/wings的submodule指向的是最新的commit。

![image](https://user-images.githubusercontent.com/73832691/176990510-f18015e3-0a7f-4945-88a2-14c835b44e2f.png)

![image](https://user-images.githubusercontent.com/73832691/176990525-19d12af6-bbbd-48ab-9e1c-ad8e57fd9734.png)

**Comment by trydofor** [comment]
没想到，这么快得到大家的抬爱。所有submodule，都是为了为了统一版本所有。因为会持续很久snapshot。现在还在构建文档和项目，主要是剥离出内部和外部，敏感信息，特殊功能等

**Comment by trydofor** [comment]
先close了，后续都会正常的。多选各位
